export interface Location {
    status: "",
    country: "",
    countryCode: "",
    region: "",
    regionName: "",
    city: "",
    zip: 0,
    lat: 0,
    lon: 0,
    timezone: "",
    isp: "",
    org: "",
    as: "",
    query: "",
    areaCode: "",
    dmaCode: 0,
    inEu: 0,
    euVaTrate: true,
    continentCode: "",
    continentName: "",
    locationAccuracyRadius: 0,
    currencyCode: "",
    currencySymbol: "",
    currencySymbolUtf8: "",
    currencyConverter: 0,
    flag: "",
    callingCode: 0,
    languageCode: "",
    security: {
      isProxy: true,
      proxyType: "",
      isCrawler: true,
      crawlerName: "",
      crawlerType: "",
      isTor: true,
      threatLevel: "",
      threatTypes: ""
    },
    connection: {
      asn: 0,
      isp: ""
    },
    type: ""
}
